const axios = require("axios");

const API_URL = "http://127.0.0.1:5000/api/students/";

const BATCH_1 = "cmslvgni80000bowomu73cuxr";
const BATCH_2 = "cmslvho820001bowo9vb7r73i";
const BATCH_3 = "cmslvk8ps0003bowod9zzacqv";

const JWT =
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.sample7.signature";

const students = [
    {
        email: "kavindu.perera.test01@example.com",
        password: "Kavindu@123",
        jwt: JWT,
        mobile: "+94771234501",
        firstName: "Kavindu",
        lastName: "Perera",
        address: "25 Flower Road, Colombo 07",
        callUpNo: "CU2026001",
        school: "Royal College Colombo",
        parentName: "Nimal Perera",
        parentMobile: "+94771234601",
        batchId: BATCH_1,
    },
    {
        email: "tharushi.fernando.test02@example.com",
        password: "Tharushi@123",
        jwt: JWT,
        mobile: "+94771234502",
        firstName: "Tharushi",
        lastName: "Fernando",
        address: "18 Park Road, Colombo 05",
        callUpNo: "CU2026002",
        school: "Musaeus College Colombo",
        parentName: "Chaminda Fernando",
        parentMobile: "+94771234602",
        batchId: BATCH_2,
    },
    {
        email: "dulanjana.bandara.test03@example.com",
        password: "Dulanjana@123",
        jwt: JWT,
        mobile: "+94771234503",
        firstName: "Dulanjana",
        lastName: "Bandara",
        address: "42 Lake Road, Kurunegala",
        callUpNo: "CU2026003",
        school: "Maliyadeva College Kurunegala",
        parentName: "Sunil Bandara",
        parentMobile: "+94771234603",
        batchId: BATCH_3,
    },
    {
        email: "senuri.wijesinghe.test04@example.com",
        password: "Senuri@123",
        jwt: JWT,
        mobile: "+94771234504",
        firstName: "Senuri",
        lastName: "Wijesinghe",
        address: "12 Temple Road, Nugegoda",
        callUpNo: "CU2026004",
        school: "Visakha Vidyalaya Colombo",
        parentName: "Ruwan Wijesinghe",
        parentMobile: "+94771234604",
        batchId: BATCH_1,
    },
    {
        email: "hirun.jayawardena.test05@example.com",
        password: "Hirun@123",
        jwt: JWT,
        mobile: "+94771234505",
        firstName: "Hirun",
        lastName: "Jayawardena",
        address: "35 Maradana Road, Colombo 10",
        callUpNo: "CU2026005",
        school: "Ananda College Colombo",
        parentName: "Ajith Jayawardena",
        parentMobile: "+94771234605",
        batchId: BATCH_2,
    },
    {
        email: "nethmi.gunasekara.test06@example.com",
        password: "Nethmi@123",
        jwt: JWT,
        mobile: "+94771234506",
        firstName: "Nethmi",
        lastName: "Gunasekara",
        address: "67 Wijerama Mawatha, Colombo 07",
        callUpNo: "CU2026006",
        school: "Devi Balika Vidyalaya Colombo",
        parentName: "Mahesh Gunasekara",
        parentMobile: "+94771234606",
        batchId: BATCH_3,
    },
    {
        email: "pasindu.rathnayake.test07@example.com",
        password: "Pasindu@123",
        jwt: JWT,
        mobile: "+94771234507",
        firstName: "Pasindu",
        lastName: "Rathnayake",
        address: "21 Peradeniya Road, Kandy",
        callUpNo: "CU2026007",
        school: "Kingswood College Kandy",
        parentName: "Sampath Rathnayake",
        parentMobile: "+94771234607",
        batchId: BATCH_1,
    },
    {
        email: "amandi.herath.test08@example.com",
        password: "Amandi@123",
        jwt: JWT,
        mobile: "+94771234508",
        firstName: "Amandi",
        lastName: "Herath",
        address: "14 Hill Street, Kandy",
        callUpNo: "CU2026008",
        school: "Girls High School Kandy",
        parentName: "Pradeep Herath",
        parentMobile: "+94771234608",
        batchId: BATCH_2,
    },
    {
        email: "chamod.dissanayake.test09@example.com",
        password: "Chamod@123",
        jwt: JWT,
        mobile: "+94771234509",
        firstName: "Chamod",
        lastName: "Dissanayake",
        address: "56 Rajapihilla Mawatha, Kandy",
        callUpNo: "CU2026009",
        school: "Dharmaraja College Kandy",
        parentName: "Ranjith Dissanayake",
        parentMobile: "+94771234609",
        batchId: BATCH_3,
    },
    {
        email: "piumi.samarasinghe.test10@example.com",
        password: "Piumi@123",
        jwt: JWT,
        mobile: "+94771234510",
        firstName: "Piumi",
        lastName: "Samarasinghe",
        address: "28 Dutugemunu Street, Colombo 08",
        callUpNo: "CU2026010",
        school: "Sirimavo Bandaranaike Vidyalaya",
        parentName: "Kumara Samarasinghe",
        parentMobile: "+94771234610",
        batchId: BATCH_1,
    },
    {
        email: "tharindu.ekanayake.test11@example.com",
        password: "Tharindu@123",
        jwt: JWT,
        mobile: "+94771234511",
        firstName: "Tharindu",
        lastName: "Ekanayake",
        address: "44 Darley Road, Colombo 10",
        callUpNo: "CU2026011",
        school: "St. Joseph's College Colombo",
        parentName: "Rohan Ekanayake",
        parentMobile: "+94771234611",
        batchId: BATCH_2,
    },
    {
        email: "sachini.madushika.test12@example.com",
        password: "Sachini@123",
        jwt: JWT,
        mobile: "+94771234512",
        firstName: "Sachini",
        lastName: "Madushika",
        address: "19 Queen Street, Gampaha",
        callUpNo: "CU2026012",
        school: "Holy Cross College Gampaha",
        parentName: "Nuwan Madushika",
        parentMobile: "+94771234612",
        batchId: BATCH_3,
    },
    {
        email: "dinuka.rajapaksha.test13@example.com",
        password: "Dinuka@123",
        jwt: JWT,
        mobile: "+94771234513",
        firstName: "Dinuka",
        lastName: "Rajapaksha",
        address: "73 Wakwella Road, Galle",
        callUpNo: "CU2026013",
        school: "Richmond College Galle",
        parentName: "Sunil Rajapaksha",
        parentMobile: "+94771234613",
        batchId: BATCH_1,
    },
    {
        email: "heshani.karunaratne.test14@example.com",
        password: "Heshani@123",
        jwt: JWT,
        mobile: "+94771234514",
        firstName: "Heshani",
        lastName: "Karunaratne",
        address: "31 Lighthouse Street, Galle",
        callUpNo: "CU2026014",
        school: "Southlands College Galle",
        parentName: "Dinesh Karunaratne",
        parentMobile: "+94771234614",
        batchId: BATCH_2,
    },
    {
        email: "isuru.wickramasinghe.test15@example.com",
        password: "Isuru@123",
        jwt: JWT,
        mobile: "+94771234515",
        firstName: "Isuru",
        lastName: "Wickramasinghe",
        address: "82 Colombo Street, Kandy",
        callUpNo: "CU2026015",
        school: "St. Anthony's College Kandy",
        parentName: "Suneth Wickramasinghe",
        parentMobile: "+94771234615",
        batchId: BATCH_3,
    },
    {
        email: "dhanushka.silva.test16@example.com",
        password: "Dhanushka@123",
        jwt: JWT,
        mobile: "+94771234516",
        firstName: "Dhanushka",
        lastName: "Silva",
        address: "15 Campbell Place, Colombo 10",
        callUpNo: "CU2026016",
        school: "Nalanda College Colombo",
        parentName: "Roshan Silva",
        parentMobile: "+94771234616",
        batchId: BATCH_1,
    },
    {
        email: "imesha.peris.test17@example.com",
        password: "Imesha@123",
        jwt: JWT,
        mobile: "+94771234517",
        firstName: "Imesha",
        lastName: "Peris",
        address: "22 Bambalapitiya Road, Colombo 04",
        callUpNo: "CU2026017",
        school: "Holy Family Convent Colombo",
        parentName: "Suresh Peris",
        parentMobile: "+94771234617",
        batchId: BATCH_2,
    },
    {
        email: "sahan.desilva.test18@example.com",
        password: "Sahan@123",
        jwt: JWT,
        mobile: "+94771234518",
        firstName: "Sahan",
        lastName: "De Silva",
        address: "38 Havelock Road, Colombo 05",
        callUpNo: "CU2026018",
        school: "Isipathana College Colombo",
        parentName: "Lal De Silva",
        parentMobile: "+94771234618",
        batchId: BATCH_3,
    },
    {
        email: "dinithi.amarasinghe.test19@example.com",
        password: "Dinithi@123",
        jwt: JWT,
        mobile: "+94771234519",
        firstName: "Dinithi",
        lastName: "Amarasinghe",
        address: "11 Bauddhaloka Mawatha, Colombo 07",
        callUpNo: "CU2026019",
        school: "Bishop's College Colombo",
        parentName: "Ramesh Amarasinghe",
        parentMobile: "+94771234619",
        batchId: BATCH_1,
    },
    {
        email: "malith.senanayake.test20@example.com",
        password: "Malith@123",
        jwt: JWT,
        mobile: "+94771234520",
        firstName: "Malith",
        lastName: "Senanayake",
        address: "45 Wakwella Road, Galle",
        callUpNo: "CU2026020",
        school: "Vidyaloka College Galle",
        parentName: "Mahinda Senanayake",
        parentMobile: "+94771234620",
        batchId: BATCH_2,
    },
    {
        email: "yasara.kumari.test21@example.com",
        password: "Yasara@123",
        jwt: JWT,
        mobile: "+94771234521",
        firstName: "Yasara",
        lastName: "Kumari",
        address: "24 Olcott Mawatha, Galle",
        callUpNo: "CU2026021",
        school: "Sanghamitta Balika Vidyalaya",
        parentName: "Ajith Kumari",
        parentMobile: "+94771234621",
        batchId: BATCH_3,
    },
    {
        email: "ravindu.fernando.test22@example.com",
        password: "Ravindu@123",
        jwt: JWT,
        mobile: "+94771234522",
        firstName: "Ravindu",
        lastName: "Fernando",
        address: "20 Galle Road, Colombo 04",
        callUpNo: "CU2026022",
        school: "St. Peter's College Colombo",
        parentName: "Nalin Fernando",
        parentMobile: "+94771234622",
        batchId: BATCH_1,
    },
    {
        email: "shenali.dias.test23@example.com",
        password: "Shenali@123",
        jwt: JWT,
        mobile: "+94771234523",
        firstName: "Shenali",
        lastName: "Dias",
        address: "66 Deal Place, Colombo 03",
        callUpNo: "CU2026023",
        school: "Ladies College Colombo",
        parentName: "Asanka Dias",
        parentMobile: "+94771234623",
        batchId: BATCH_2,
    },
    {
        email: "keshan.abeysekara.test24@example.com",
        password: "Keshan@123",
        jwt: JWT,
        mobile: "+94771234524",
        firstName: "Keshan",
        lastName: "Abeysekara",
        address: "17 College Avenue, Mount Lavinia",
        callUpNo: "CU2026024",
        school: "St. Thomas' College Mount Lavinia",
        parentName: "Kamal Abeysekara",
        parentMobile: "+94771234624",
        batchId: BATCH_3,
    },
    {
        email: "manudi.weerasinghe.test25@example.com",
        password: "Manudi@123",
        jwt: JWT,
        mobile: "+94771234525",
        firstName: "Manudi",
        lastName: "Weerasinghe",
        address: "33 Bauddhaloka Mawatha, Colombo 07",
        callUpNo: "CU2026025",
        school: "Devi Balika Vidyalaya",
        parentName: "Prasanna Weerasinghe",
        parentMobile: "+94771234625",
        batchId: BATCH_1,
    },
    {
        email: "rashan.gunawardena.test26@example.com",
        password: "Rashan@123",
        jwt: JWT,
        mobile: "+94771234526",
        firstName: "Rashan",
        lastName: "Gunawardena",
        address: "12 Moragahahena Road, Horana",
        callUpNo: "CU2026026",
        school: "Taxila Central College Horana",
        parentName: "Chandana Gunawardena",
        parentMobile: "+94771234626",
        batchId: BATCH_2,
    },
    {
        email: "ayesha.nawaz.test27@example.com",
        password: "Ayesha@123",
        jwt: JWT,
        mobile: "+94771234527",
        firstName: "Ayesha",
        lastName: "Nawaz",
        address: "41 Messenger Street, Colombo 12",
        callUpNo: "CU2026027",
        school: "Muslim Ladies College Colombo",
        parentName: "Mohamed Nawaz",
        parentMobile: "+94771234627",
        batchId: BATCH_3,
    },
    {
        email: "nipun.madushan.test28@example.com",
        password: "Nipun@123",
        jwt: JWT,
        mobile: "+94771234528",
        firstName: "Nipun",
        lastName: "Madushan",
        address: "9 Main Street, Gampaha",
        callUpNo: "CU2026028",
        school: "Bandaranayake College Gampaha",
        parentName: "Kamal Madushan",
        parentMobile: "+94771234628",
        batchId: BATCH_1,
    },
    {
        email: "sewmi.lakshani.test29@example.com",
        password: "Sewmi@123",
        jwt: JWT,
        mobile: "+94771234529",
        firstName: "Sewmi",
        lastName: "Lakshani",
        address: "29 Queen Mary Road, Gampaha",
        callUpNo: "CU2026029",
        school: "Rathnavali Balika Vidyalaya",
        parentName: "Ruwan Lakshani",
        parentMobile: "+94771234629",
        batchId: BATCH_2,
    },
    {
        email: "akila.prasad.test30@example.com",
        password: "Akila@123",
        jwt: JWT,
        mobile: "+94771234530",
        firstName: "Akila",
        lastName: "Prasad",
        address: "16 Station Road, Colombo",
        callUpNo: "CU2026030",
        school: "Dudley Senanayake Central College",
        parentName: "Pradeep Prasad",
        parentMobile: "+94771234630",
        batchId: BATCH_3,
    },
    {
        email: "himashi.peiris.test31@example.com",
        password: "Himashi@123",
        jwt: JWT,
        mobile: "+94771234531",
        firstName: "Himashi",
        lastName: "Peiris",
        address: "30 Queen's Road, Colombo 03",
        callUpNo: "CU2026031",
        school: "St. Bridget's Convent Colombo",
        parentName: "Dilan Peiris",
        parentMobile: "+94771234631",
        batchId: BATCH_1,
    },
    {
        email: "janith.ranatunga.test32@example.com",
        password: "Janith@123",
        jwt: JWT,
        mobile: "+94771234532",
        firstName: "Janith",
        lastName: "Ranatunga",
        address: "18 Thurstan Road, Colombo 07",
        callUpNo: "CU2026032",
        school: "Thurstan College Colombo",
        parentName: "Sunil Ranatunga",
        parentMobile: "+94771234632",
        batchId: BATCH_2,
    },
    {
        email: "dewmini.wijeratne.test33@example.com",
        password: "Dewmini@123",
        jwt: JWT,
        mobile: "+94771234533",
        firstName: "Dewmini",
        lastName: "Wijeratne",
        address: "8 Peradeniya Road, Kandy",
        callUpNo: "CU2026033",
        school: "Pushpadana Girls College Kandy",
        parentName: "Ajith Wijeratne",
        parentMobile: "+94771234633",
        batchId: BATCH_3,
    },
    {
        email: "kavisha.seneviratne.test34@example.com",
        password: "Kavisha@123",
        jwt: JWT,
        mobile: "+94771234534",
        firstName: "Kavisha",
        lastName: "Seneviratne",
        address: "27 Main Street, Kegalle",
        callUpNo: "CU2026034",
        school: "Kegalu Vidyalaya",
        parentName: "Nuwan Seneviratne",
        parentMobile: "+94771234634",
        batchId: BATCH_1,
    },
    {
        email: "oshan.lakmal.test35@example.com",
        password: "Oshan@123",
        jwt: JWT,
        mobile: "+94771234535",
        firstName: "Oshan",
        lastName: "Lakmal",
        address: "13 Beach Road, Matara",
        callUpNo: "CU2026035",
        school: "St. Servatius College Matara",
        parentName: "Ranjith Lakmal",
        parentMobile: "+94771234635",
        batchId: BATCH_2,
    },
    {
        email: "hansika.ruwanthi.test36@example.com",
        password: "Hansika@123",
        jwt: JWT,
        mobile: "+94771234536",
        firstName: "Hansika",
        lastName: "Ruwanthi",
        address: "32 Akuressa Road, Matara",
        callUpNo: "CU2026036",
        school: "Sujatha Vidyalaya Matara",
        parentName: "Sunil Ruwanthi",
        parentMobile: "+94771234636",
        batchId: BATCH_3,
    },
    {
        email: "gihan.wimalasena.test37@example.com",
        password: "Gihan@123",
        jwt: JWT,
        mobile: "+94771234537",
        firstName: "Gihan",
        lastName: "Wimalasena",
        address: "55 Ananda Rajakaruna Mawatha, Colombo",
        callUpNo: "CU2026037",
        school: "Nalanda College Colombo",
        parentName: "Mahesh Wimalasena",
        parentMobile: "+94771234637",
        batchId: BATCH_1,
    },
    {
        email: "yohan.wijesuriya.test41@example.com",
        password: "Yohan@123",
        jwt: JWT,
        mobile: "+94771234541",
        firstName: "Yohan",
        lastName: "Wijesuriya",
        address: "17 Station Road, Moratuwa",
        callUpNo: "CU2026041",
        school: "Prince of Wales College Moratuwa",
        parentName: "Ruwan Wijesuriya",
        parentMobile: "+94771234641",
        batchId: BATCH_2,
    },
    {
        email: "nimasha.kavindi.test42@example.com",
        password: "Nimasha@123",
        jwt: JWT,
        mobile: "+94771234542",
        firstName: "Nimasha",
        lastName: "Kavindi",
        address: "38 Horana Road, Panadura",
        callUpNo: "CU2026042",
        school: "Panadura Balika Vidyalaya",
        parentName: "Chamara Kavindi",
        parentMobile: "+94771234642",
        batchId: BATCH_3,
    },
    {
        email: "ravishka.perera.test43@example.com",
        password: "Ravishka@123",
        jwt: JWT,
        mobile: "+94771234543",
        firstName: "Ravishka",
        lastName: "Perera",
        address: "61 Rawathawatta Road, Moratuwa",
        callUpNo: "CU2026043",
        school: "St. Sebastian's College Moratuwa",
        parentName: "Saman Perera",
        parentMobile: "+94771234643",
        batchId: BATCH_1,
    },
    {
        email: "ashen.sirisena.test44@example.com",
        password: "Ashen@123",
        jwt: JWT,
        mobile: "+94771234544",
        firstName: "Ashen",
        lastName: "Sirisena",
        address: "22 R. A. De Mel Mawatha, Colombo 03",
        callUpNo: "CU2026044",
        school: "Mahanama College Colombo",
        parentName: "Anura Sirisena",
        parentMobile: "+94771234644",
        batchId: BATCH_2,
    },
    {
        email: "sithumini.weerasekara.test45@example.com",
        password: "Sithumini@123",
        jwt: JWT,
        mobile: "+94771234545",
        firstName: "Sithumini",
        lastName: "Weerasekara",
        address: "14 High Level Road, Nugegoda",
        callUpNo: "CU2026045",
        school: "Anula Vidyalaya Nugegoda",
        parentName: "Pradeep Weerasekara",
        parentMobile: "+94771234645",
        batchId: BATCH_3,
    },
    {
        email: "naveen.alwis.test46@example.com",
        password: "Naveen@123",
        jwt: JWT,
        mobile: "+94771234546",
        firstName: "Naveen",
        lastName: "Alwis",
        address: "7 College Road, Mount Lavinia",
        callUpNo: "CU2026046",
        school: "St. Thomas' College Mount Lavinia",
        parentName: "Dinesh Alwis",
        parentMobile: "+94771234646",
        batchId: BATCH_1,
    },
    {
        email: "kavindi.dissanayake.test47@example.com",
        password: "Kavindi@123",
        jwt: JWT,
        mobile: "+94771234547",
        firstName: "Kavindi",
        lastName: "Dissanayake",
        address: "45 Vajira Road, Colombo 04",
        callUpNo: "CU2026047",
        school: "Visakha Vidyalaya Colombo",
        parentName: "Suresh Dissanayake",
        parentMobile: "+94771234647",
        batchId: BATCH_2,
    },
    {
        email: "rukshan.jayasuriya.test48@example.com",
        password: "Rukshan@123",
        jwt: JWT,
        mobile: "+94771234548",
        firstName: "Rukshan",
        lastName: "Jayasuriya",
        address: "62 Gregory's Road, Colombo 07",
        callUpNo: "CU2026048",
        school: "D. S. Senanayake College",
        parentName: "Rohan Jayasuriya",
        parentMobile: "+94771234648",
        batchId: BATCH_3,
    },
    {
        email: "shamali.gunawardhana.test49@example.com",
        password: "Shamali@123",
        jwt: JWT,
        mobile: "+94771234549",
        firstName: "Shamali",
        lastName: "Gunawardhana",
        address: "17 Kandy Road, Gampaha",
        callUpNo: "CU2026049",
        school: "Rathnavali Balika Vidyalaya",
        parentName: "Chandima Gunawardhana",
        parentMobile: "+94771234649",
        batchId: BATCH_1,
    },
    {
        email: "dinesh.kumara.test50@example.com",
        password: "Dinesh@123",
        jwt: JWT,
        mobile: "+94771234550",
        firstName: "Dinesh",
        lastName: "Kumara",
        address: "10 Richmond Hill Road, Galle",
        callUpNo: "CU2026050",
        school: "Mahinda College Galle",
        parentName: "Sunil Kumara",
        parentMobile: "+94771234650",
        batchId: BATCH_2,
    },
];

describe("POST /api/students/", () => {
    test.each(students)(
        "should create student $callUpNo - $firstName $lastName",
        async (student) => {
            const response = await axios.post(API_URL, student, {
                validateStatus: () => true,
            });

            console.log(
                `${student.callUpNo}: ${response.status} - ${response.data.msg}`
            );

            expect(response.status).toBe(201);

            expect(response.data.success).toBe(true);

            expect(response.data.msg).toBe(
                "Student created successfully"
            );

            expect(response.data.data).toBeDefined();

            expect(response.data.data.user).toBeDefined();

            expect(response.data.data.student).toBeDefined();

            // User response
            expect(response.data.data.user.email).toBe(
                student.email
            );

            expect(response.data.data.user.mobile).toBe(
                student.mobile
            );

            expect(response.data.data.user.first_name).toBe(
                student.firstName
            );

            expect(response.data.data.user.last_name).toBe(
                student.lastName
            );

            expect(response.data.data.user.address).toBe(
                student.address
            );

            expect(response.data.data.user.roles).toBe(
                "student"
            );

            expect(response.data.data.user.is_active).toBe(true);

            expect(response.data.data.user.gAuthID).toBeDefined();

            expect(response.data.data.user.id).toBeDefined();

            expect(response.data.data.user.createdAt).toBeDefined();

            // Student response
            expect(response.data.data.student.call_up_no).toBe(
                student.callUpNo
            );

            expect(response.data.data.student.school).toBe(
                student.school
            );

            expect(response.data.data.student.parent_name).toBe(
                student.parentName
            );

            expect(response.data.data.student.parent_mobile).toBe(
                student.parentMobile
            );

            expect(response.data.data.student.batch_id).toBe(
                student.batchId
            );

            expect(response.data.data.student.user_id).toBe(
                response.data.data.user.id
            );
        }
    );
});